# Generated by Django 5.1.6 on 2025-03-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Filme',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Filme',
            field=models.ManyToManyField(to='usuarios.filmes'),
        ),
    ]
